//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicagoInABox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int LineID { get; set; }
        public int OrderID { get; set; }
        public decimal Quantity { get; set; }
        public int ItemID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
