//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicagoInABox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public int ShipToID { get; set; }
        public int BillToID { get; set; }
        public int OrderQty { get; set; }
        public int OrderSize { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Notes { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}
