//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicagoInABox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentID { get; set; }
        public string PaymentMethod { get; set; }
        public decimal PaymentAmt { get; set; }
        public int OrderID { get; set; }
        public int StripeChargeID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
